import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

// Will be generated by build_runner
part 'drift_database.g.dart';

/// Educational Note:
/// Drift provides a type-safe wrapper around SQLite.
/// We define tables as Dart classes.
class DriftProducts extends Table {
  /// Step 1: Define Table Schema using Dart getters.
  /// Drift reads this class and generates type-safe SQL queries and models.
  TextColumn get id => text()();
  TextColumn get name => text()();
  RealColumn get price => real()();

  @override
  Set<Column> get primaryKey => {id};
}

@DriftDatabase(tables: [DriftProducts])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  // Stream queries (Reactive)
  /// Step 2: Reactive Streams
  /// Drift automatically watches tables for changes. When data is inserted/deleted,
  /// this stream yields the new list, updating the UI instantly without manual refreshes.
  Stream<List<DriftProduct>> watchAllProducts() => select(driftProducts).watch();

  // Future queries
  Future<List<DriftProduct>> getAllProducts() => select(driftProducts).get();

  // Insert/Update
  /// Step 3: Type-safe Insert
  /// Instead of `INSERT INTO table...`, we pass the generated `DriftProduct` model.
  /// `InsertMode.insertOrReplace` handles Upsert logic.
  Future<void> insertOrUpdateProduct(DriftProduct product) {
    return into(driftProducts).insert(product, mode: InsertMode.insertOrReplace);
  }

  // Delete
  /// Step 4: Type-safe Where clauses
  /// Drift prevents syntax errors because column names like `t.id` are verified at compile time.
  Future<void> deleteProduct(String id) {
    return (delete(driftProducts)..where((t) => t.id.equals(id))).go();
  }

  // Clear Table
  Future<void> clearProducts() {
    return delete(driftProducts).go();
  }
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}
