import 'package:hive/hive.dart';

part 'hive_product.g.dart'; // Will be generated by build_runner

@HiveType(typeId: 0)
class HiveProduct extends HiveObject {
  @HiveField(0)
  late String id;

  @HiveField(1)
  late String name;

  @HiveField(2)
  late double price;

  HiveProduct({
    required this.id,
    required this.name,
    required this.price,
  });

  @override
  String toString() {
    return 'HiveProduct(id: $id, name: $name, price: $price)';
  }
}
