import 'package:isar/isar.dart';

part 'isar_product.g.dart'; // Will be generated by build_runner

@collection
class IsarProduct {
  Id id = Isar.autoIncrement; // Isar requires a 64-bit int ID

  @Index() // We can index fields for faster lookup
  late String name;

  late double price;
}
